FROM mcr.microsoft.com/devcontainers/javascript-node:0-18
#FROM mcr.microsoft.com/devcontainers/base:alpine-3.20

#WORKDIR 

#RUN apt-get update && export DEBIAN_FRONTEND=noninteractive && apt-get -y install git
